### ISSUE TITLE
Unable to get it to run on windows

### ISSUE THREAD

**Issue by 4imble** [jakkn/nwn-devbase#15]
Have docker,
Running linux containers.
Open powershell and run this:
`function nwn-build {docker run --rm -it -v \"$(pwd):/home/devbase/build\" jakkn/nwn-devba
se}` 

then:
 `nwn-build`

Errors with: `The source path "\\C:\\Git\\nwn-module-path" is not a valid Windows path.`

I removed the backslashes and ran again: 
`function nwn-build {docker run --rm -it -v "$(pwd):/home/devbase/build" jakkn/nwn-devba
se}` 

and again:
 `nwn-build`

This time I get the error: 
```
Traceback (most recent call last):
        9: from /usr/local/bin/nwn-build:493:in `<main>'
        8: from /usr/local/bin/nwn-build:447:in `pack_all'
        7: from /usr/local/bin/nwn-build:241:in `init_directories'
        6: from /usr/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
        5: from /usr/lib/ruby/2.5.0/fileutils.rb:193:in `each'
        4: from /usr/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
        3: from /usr/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
        2: from /usr/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
        1: from /usr/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
/usr/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Permission denied @ dir_s_mkdir - /home/devbase/build/server (Errno::EACCES)
```

Not sure how to resolve this one, any ideas?

**Comment by jakkn** [comment]
Hi @4imble! Sorry for the late response, I got no email about this so I have to look over my notification settings.

I don't use PowerShell to run the docker command myself so this is unknown territory to me. But the permission denied error is thrown by ruby so the container is spinning up and the script fails when it tries to create the `server` dir in the mounted volume. I suggest attaching to the container by running `docker run --rm -it -v \"$(pwd):/home/devbase/build\" --entrypoint /bin/bash jakkn/nwn-devbase` and poke around. What does `ls /home/devbase/build` give? Can you `mkdir /home/devbase/build/tmp`?

And I notice there's a space at the end of your command, but I recon that is a typo since docker should fail to run that image and the trailing 'se' should make the function blow up.

**Comment by 4imble** [comment]
Cheers for that, I will try when I am back on my windows machine. I have actually changed over to Linux on my main machine (to get more practice) so will try on that too when I can work out how to get the toolset running there as well.

**Comment by jakkn** [comment]
Linux is definitely easier, but it should work on windows too so I'm happy to help out. I'll leave the issue open for now.

**Comment by jakkn** [comment]
Closing due to inactivity.

**Comment by 4imble** [comment]
I think part of my problem is mounts don't work too well on windows into
Linux contaners. I had big problems with this on something else I used
docker for.

**Comment by jakkn** [comment]
Yeah I run into similar quirks on regular intervals. Reading linux files from a windows partition is far from ideal.
